### ISSUE TITLE
VirusTotal detection

### ISSUE THREAD

**Issue by MrZsemle** [composer/windows-setup#101]
# Hello!

I noticed that VirusTotal detects the installer as an unwanted file, so I don't really want to install Composer. Do you know anything about this? Intentionally added it the installer? Or why is that is? Thank you in advance for your reply.

[VirusTotal detection](https://www.virustotal.com/gui/file/0b00f156edd116a7f464b6a17938568a1c1d71e93365104aa862351b2cf660e9/detection)

**Comment by johnstevenson** [comment]
> Do you know anything about this? Intentionally added it the installer?

If you mean, have I deliberately included malware in the installer then obviously the answer is no. I've code-signed the binary myself.

It is apparently a new scanning engine (Secure Age), only added to VirusTotal since May 2019. I see that Chocolatey still says it is okay (although clicking on the link shows the same VirusTotal result): https://chocolatey.org/packages/composer

However the [Nuget ](https://www.virustotal.com/file/6352e24c25f285e0e70d5b68b07e76e1e1d8047a38a998a6f44b34573a1f149b/analysis/) container package (which is required for Chocolatey) doesn't fail and this includes the Composer-Setup.exe binary.

I've reported this to Secure Age as a false positive.

**Comment by MrZsemle** [comment]
Thank you!

**Comment by MrZsemle** [comment]
Could Inno Setup have anything to do with this?

**Comment by johnstevenson** [comment]
Whenever I have uploaded a new version to Chocolatey it invariably throws up some false positives on VirusTotal. By the time Chocolatey have got around to approving the package, most of these have disappeared. A few weeks later and there are none. Go figure.

So it does not seem a very foolproof system to me.

If the new engine is considering Inno Setup itself as a threat, then they are going to throw up a hell of a lot of false positives. And this wouldn't explain why the Nuget Package, which is a wrapper around the same (Inno Setup) binary, doesn't show a similar result. Perhaps this engine is not very good (yet)?

**Comment by johnstevenson** [comment]
Response from Secure Age (30-08-2019):

> Your submission (20190827-201018419000/Composer-Setup.4.10.0.zip) has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us at qa@secureage.com if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result.

**Comment by MrZsemle** [comment]
Excuse me, can I get a link to the zip file in the previous answer?

**Comment by johnstevenson** [comment]
I just sent them Composer-Setup.4.10.0.exe (zipped, as per their reporting instructions).
