### ISSUE TITLE
The Composer installer script was not successful [exit code 1].

### ISSUE THREAD

**Issue by OXRA-SB** [composer/windows-setup#159]
Здравствуйте, когда пытаюсь установить composer, выходит такая ошибка:

The Composer installer script was not successful [exit code 1].

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo for getcomposer.org failed: Обычно - это временная ошибка, возникающая во время разрешения имени узла, и означающая, что локальный сервер не получил ответа от полномочного сервера.

Как решить данную проблему?

![прокси](https://github.com/user-attachments/assets/74837f53-d459-4d75-8af8-95c82f59991e)

**Comment by johnstevenson** [comment]
This means that the DNS lookup to resolve the host name `getcomposer.org` failed.

This could either be caused by a misconfiguration in the DNS service on your computer or an external DNS server failing.

Perhaps something has been added to your `Windows\System32\Drivers\etc\hosts` file that is causing a problem?
