### ISSUE TITLE
Installing windows version of composer

### ISSUE THREAD

**Issue by paladox** [composer/windows-setup#53]
Hi with the new release of composer using the windows installer it no longer upgrades prevous version ofs composer.

Also the option that allowed users to add composer to the windows options meaning when you right clicked on the folder for which you want to run composer it used to show the option to do composer install or run composer. Now it doesn't show the option.

Please fix this.

**Comment by johnstevenson** [comment]
What exactly do you mean by "no longer upgrades previous version of composer"?

**Comment by paladox** [comment]
@johnstevenson when I clicked download from your website for windows. It said I had to go to control panel first then uninstall composer first. Probaly related to the removal of shell menus which requires removal.

Please could you revert https://github.com/composer/windows-setup/commit/7edd75a0d598d621d1ab8188803df192d497daca since I used it In the windows context menu please.

**Comment by johnstevenson** [comment]
Ah, okay. If you need the shell menus, you can download v3.0 from the releases. If you haven't got openssl enabled, it won't work though.

**Comment by paladox** [comment]
@johnstevenson why was it removed and can it be added back or could something that works similar be added.

**Comment by johnstevenson** [comment]
Which particular feature did you find useful?

**Comment by paladox** [comment]
@johnstevenson having the ability to right click on a folder or file I think and then click run composer.

**Comment by johnstevenson** [comment]
- Shift right-click: `Open command window here`
- with Git for Windows: `Git Bash Here`.

**Comment by lyz452** [comment]
Clearly, they just don't want to maintain it...

**Comment by johnstevenson** [comment]
@lyz452 Maintaining it wasn't the issue here, rather it was incorporating it into Composer-Setup itself. This is averagely complicated and made it harder to upgrade the core functionality of the installer.

In addition, because the extension gets loaded into Windows Explorer, the install/uninstall process would sometimes not work. Even though we used the Windows RestartManager API (which was designed for such purposes) you could easily end up with your desktop Window disappearing.

Git for Windows found similar problems with its Git Cheetah extension, and subsequently dropped it.

However, there is obviously an interest in using it. I have considered offering the Shell Menus in a separate installer. Can you tell me how it helps you in your day to day usage of Composer. What are the commands that you find the most useful?

**Comment by lyz452** [comment]
That's good reason. Sorry I had doubts. I just like to keep the command line stuff to the minimum. I didn't know about the shift + right click thing so I should stop complaining now.

**Comment by chrisx84** [comment]
i found the shell menu useful to but shift+right click and opening powershell is fine after understanding why the shell menu option was removed. #DamnYouWindows
