### ISSUE TITLE
could we please have the context menu back in the windows installer

### ISSUE THREAD

**Issue by mcbmcb0** [composer/windows-setup#61]
I know the windows installer context menu option was removed - could we please have it back in the windows installer? it was very useful

thanks!

**Comment by johnstevenson** [comment]
Which particular feature did you find useful? You can easily open a command window from the File Explorer and run any composer command you wish:

- Shift right-click: `Open command window here`
- Right-click: `Git Bash Here` (using Git for Windows)

**Comment by mcbmcb0** [comment]
well... i think i'm just very lazy and forgetful, hence found a composer context menu item easier to find/remember - especially as I don't use composer a lot. but you are right the command prompt is there on shift-right-click. i had also thought composer needed an admin command prompt in windows but just tried it and it didn't.
so... i still think it was a great convenient feature and would like to see it again, and can probably live without it.
thanks for considering it...!

**Comment by mi32dogs** [comment]
Here is my two cent’s on this;
Why would you take it away? Yes you can open a command window easily, fine if that is how you like to use it, use it that way, but there are lots of people that are not fully comfortable with the command prompt, and do not remember all the calls as they do not work with it every day, so  why do you take it away for those people? Is it in your way if it is in the context menu? NO.
If you do not want to use the context menu then don’t use it, and If there is a technical issue that’s one thing, but just taking it away because YOU don’t need it seems silly and elitist to me. 
Composer ought be for everybody, not just for the elite programmer but also for the weekend warrior, or my dad who likes to play around with computers.

**Comment by mcbmcb0** [comment]
Hi mi32dogs.
i get where you are coming but don't you think its amazing that people make great software like composer for free and give it away to people like us to use? sure it could be a bit more friendly for linux-phobic-types (like me) but even if it isn't we can stumble through. and even learn more about windows in the process.

Composer + github = 1000's of awesome open-source packages for you and me to use as we wish... big respect for  people who make this all possible.
(i'm the guy who started this thread)

**Comment by johnstevenson** [comment]
> If there is a technical issue that’s one thing,

There was. Please read this: https://github.com/composer/windows-setup/issues/53#issuecomment-270747101

@mi32dogs Could you please tell me how it helps you in your day to day usage of Composer. What are the commands that you find the most useful?

As I said in the comment I could offer the Shell Menus in a separate installer. But I _really_ need to know what people miss (other than the `Composer here` functionality)
