### ISSUE TITLE
The PHP exe file you specified did not run correctly [exit code 1]:

### ISSUE THREAD

**Issue by allyg90** [composer/windows-setup#76]
I got error:
The PHP exe file you specified did not run correctly [exit code 1]:
C:\xampp\php\php.exe

No output was returned.

I attached the log file.

[Setup Log 2017-10-05 #001.txt](https://github.com/composer/windows-setup/files/1361513/Setup.Log.2017-10-05.001.txt)

**Comment by johnstevenson** [comment]
Thanks for reporting this and submitting a log file, because I can see exactly what is happening now:

If the username contains an `&` character, then any cmd.exe arguments that include this path will be split. The remedy is either not to use the full path, or to correctly escape the arguments.

I'll fix this ASAP.

**Comment by allyg90** [comment]
Yup, I had to set up a new user in my computer and it worked perfectly! 
Thank you!

**Comment by johnstevenson** [comment]
Fixed in https://github.com/composer/windows-setup/releases/tag/v4.8.0

Thanks again for taking the time to provide the log file, even though you had managed to get around the problem. Often folks report an issue, then never reply to requests for more info (presumably because they've sorted it), which I find incredibly annoying - but, hey ho!
