### ISSUE TITLE
The PHP exe file you specified did not run correctly [exit code 1]

### ISSUE THREAD

**Issue by CJDennis** [composer/windows-setup#80]
I suspect it's failing because my user name has been rendered as `DANIEL~1.KLE`. On an almost identical setup with the user name `Daniel`, it worked perfectly.

[Setup Log 2017-10-25 #002.txt](https://github.com/composer/windows-setup/files/1413163/Setup.Log.2017-10-25.002.txt)

**Comment by johnstevenson** [comment]
Have you got ANSICON installed? Because this hooks into cmd.exe and appears to return exit code `1` for calls that it makes (overriding what the called program returned - for some reason). In this case ComposerSetup assumes that its own call has failed, hence the error message.

See https://github.com/composer/windows-setup/issues/74

**Comment by CJDennis** [comment]
Yes, however, both setups had ANSICON installed at the time. I managed to get Composer to install by creating another Windows account with a simpler user name.

**Comment by johnstevenson** [comment]
Thanks. I don't think the account name is the problem though, if you don't mind bearing with me (I would really like to get to the bottom of this);

From your log:
```
2017-10-25 13:42:29.862   $ Checking php configuration
2017-10-25 13:42:29.862   $ -- Execute File --
2017-10-25 13:42:29.862   $ Running C:\WINDOWS\system32\cmd.exe /c "C:\server\php5.05.09\php.exe check.php > C:\Users\DANIEL~1.KLE\AppData\Local\Temp\is-IC2B8.tmp\stdout.txt 2> C:\Users\DANIEL~1.KLE\AppData\Local\Temp\is-IC2B8.tmp\stderr.txt"
2017-10-25 13:42:29.944   $ Success: exit code [1]
2017-10-25 13:42:29.945   $ Output from stdout [54 bytes]
                          <ComposerSetup:>5.5.9|C:\server\php5.05.09\php.ini|1|1
2017-10-25 13:42:29.945   $ Output from stderr [0 bytes]
2017-10-25 13:42:29.945   $ Error: [ERR_CHECK_PHP]
                          The PHP exe file you specified did not run correctly [exit code 1]:
```
This shows that your php.exe successfully ran the installer's `check.php` script and, via cmd.exe, piped its output correctly to the 2 temporary txt files. There is nothing reported in stderr and the value from stdout is perfect:

```
<ComposerSetup:>5.5.9|C:\server\php5.05.09\php.ini|1|1
```
The problem is that the installer received a non-zero exit code, which is strange because  `check.php` explicitly calls `exit(0)`. The fact that we got the correct output demonstrates that there is nothing wrong with the filenames passed to cmd.exe

So I have to assume that ANSICON is causing this. However, I cannot reproduce this, so could you please tell me what version of ANSICON you are using and how it is installed. The value/existence of the following AutoRun registry keys would also be very helpful:

```
HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Command Processor\AutoRun
```
and for each relevant user:

```
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
```

**Comment by CJDennis** [comment]
It appears you might be right. ANSICON is not active for the other user. The version is 1.66, which I believe is the most recent version. It was installed via the command prompt by running `ansicon.exe -i`.

I have created an issue at https://github.com/adoxa/ansicon/issues/108

- HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun does not exist
- HKEY_LOCAL_MACHINE\Software\WOW6432Node does not exist
- HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun = (if %ANSICON_VER%==^%ANSICON_VER^% "C:\Windows\System32\ANSICON\x64\ansicon" -p)

I haven't checked (for the existence of) the last key for the other user since I never installed it there.

**Comment by johnstevenson** [comment]
Great stuff, thanks. I can finally reproduce this now - the location in `C:\Windows` makes the difference. I'll report this in the issue you created. The next release of the installer (4.8.0) will handle this by showing a more meaningful error message, as per this beta:

https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.7.1.exe

**Comment by johnstevenson** [comment]
I've added a warning to the error message about installing ansicon to the system directory. https://github.com/composer/windows-setup/commit/8a9dd421b6f15472d54d1d9151f23f0240066d80

Thanks for helping with this.
